#! /usr/bin/bash

IS_ARCH=0

if command -v "pacman" &> /dev/null
then
  IS_ARCH=1
fi

for filename in ./packages/*; do
  source "$filename"

  if [ "$IS_ARCH" -eq 1 ]; then
    install
  fi

  configure

  unset -f install
  unset -f configure
done

other_packages=(
  exa
  bat
  fd
  ripgrep
  fzf
  lazygit
)

if [ "$IS_ARCH" -eq 1 ]; then
  for package in "${other_packages[@]}"
  do
    sudo pacman -S "$package" --noconfirm
  done
fi
