#! /usr/bin/bash

git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.9.0

mkdir -p ~/.config/fish/completions
ln -s ~/.asdf/completions/asdf.fish ~/.config/fish/completions

source ~/.bashrc

asdf install python 3.9.9
asdf install ruby 3.0.1
asdf install nodejs 16.13.2
asdf install java openjdk-11.0.2

asdf global python 3.9.9
asdf global ruby 3.0.1
asdf global nodejs 16.13.2
asdf global java openjdk-11.0.2
