#! /usr/bin/bash

rm -rf ~/.config/nvim

git clone https://github.com/leoncruz/nvim-config ~/.config/nvim

sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.config}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
